name: 'Network - NetworkWatchers'

parameters:
  - name: removeDeployment
    displayName: Remove deployed module
    type: boolean
    default: false # Only one Network Watcher can exist in the same location. If removed, a default would be created in a dedicated RG
  - name: prerelease
    displayName: Publish prerelease module
    type: boolean
    default: false

pr: none

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - '/.azuredevops/modulePipelines/ms.network.networkwatchers.yml'
      - '/.azuredevops/pipelineTemplates/*.yml'
      - '/modules/Microsoft.Network/networkWatchers/*'
      - '/utilities/pipelines/*'
    exclude:
      - '/utilities/pipelines/dependencies/*'
      - '/**/*.md'

variables:
  - template: '../../settings.yml'
  - group: 'PLATFORM_VARIABLES'
  - name: modulePath
    value: '/modules/Microsoft.Network/networkWatchers'

stages:
  - template: /.azuredevops/pipelineTemplates/stages.module.yml
    parameters:
      removeDeployment: '${{ parameters.removeDeployment }}'
      prerelease: '${{ parameters.prerelease }}'
