name: '.Platform - Update ReadMe Module Tables'

pr: none

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - 'modules/**/deploy.bicep'
      - 'modules/**/deploy.json'
      - 'utilities/tools/platform/**'

variables:
  - template: '../../settings.yml'
  - name: pipelinePrincipalGitUserName
    value: 'CARMLPipelinePrincipal'
  - name: pipelinePrincipalGitUserEmail
    value: 'CARML@noreply.github.com'
  - name: relativeScriptPath_SetReadMeModuleTable
    value: 'utilities/tools/platform/Set-ReadMeModuleTable.ps1'
  - name: relativeScriptPath_SetModuleOverviewTable
    value: 'utilities/tools/platform/Set-ModuleOverviewTable.ps1'

jobs:
  - job: Update_module_tables
    pool:
      ${{ if ne(variables.vmImage, '') }}:
        vmImage: ${{ variables.vmImage }}
      ${{ if ne(variables.poolName, '') }}:
        name: ${{ variables.poolName }}
    steps:
      - checkout: self
        persistCredentials: true
      - task: PowerShell@2
        displayName: 'Update general ReadMe'
        inputs:
          targetType: inline
          pwsh: true
          script: |
            # Load used functions
            . (Join-Path '$(System.DefaultWorkingDirectory)' '$(relativeScriptPath_SetReadMeModuleTable)')

            $functionInput = @{
              ModulesPath    = Join-Path '$(System.DefaultWorkingDirectory)' 'modules'
              FilePath       = Join-Path '$(System.DefaultWorkingDirectory)' 'README.md'
              Organization   = '$(System.CollectionUri)'.Split('/')[3]
              RepositoryName = '$(Build.Repository.Name)'
              ColumnsInOrder = @('Name', 'Status')
              SortByColumn   = 'Name'
              Environment    = 'ADO'
              ProjectName    = '$(System.TeamProject)'
            }

            Write-Verbose "Invoke task with" -Verbose
            Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose

            Set-ReadMeModuleTable @functionInput -Verbose
      - task: PowerShell@2
        displayName: 'Update module folder ReadMe'
        inputs:
          targetType: inline
          pwsh: true
          script: |
            # Load used functions
            . (Join-Path '$(System.DefaultWorkingDirectory)' '$(relativeScriptPath_SetReadMeModuleTable)')

            $functionInput = @{
              ModulesPath    = Join-Path '$(System.DefaultWorkingDirectory)' 'modules'
              FilePath       = Join-Path '$(System.DefaultWorkingDirectory)' 'modules' 'README.md'
              Organization   = '$(System.CollectionUri)'.Split('/')[3]
              RepositoryName = '$(Build.Repository.Name)'
              ColumnsInOrder = @('Name', 'ProviderNamespace','ResourceType')
              Environment    = 'ADO'
              ProjectName    = '$(System.TeamProject)'
            }

            Write-Verbose "Invoke task with" -Verbose
            Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose

            Set-ReadMeModuleTable @functionInput -Verbose

      - task: PowerShell@2
        displayName: 'Update module outline'
        inputs:
          targetType: inline
          pwsh: true
          script: |
            # Load used functions
            . (Join-Path '$(System.DefaultWorkingDirectory)' '$(relativeScriptPath_SetModuleOverviewTable)')

            $functionInput = @{
              MarkdownFilePath = Join-Path '$(System.DefaultWorkingDirectory)' 'docs' 'wiki' 'The library - Module overview.md'
              ModuleFolderPath = Join-Path '$(System.DefaultWorkingDirectory)' 'modules'
            }

            Write-Verbose "Invoke task with" -Verbose
            Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose

            Set-ModuleOverviewTable @functionInput -Verbose

      - task: PowerShell@2
        displayName: 'Push changes'
        inputs:
          targetType: inline
          pwsh: true
          script: |
            git config --global user.email '$(pipelinePrincipalGitUserEmail)'
            git config --global user.name '$(pipelinePrincipalGitUserName)'
            Write-Verbose '$(Build.SourceBranch)' -Verbose
            git add .
            git commit -m "Push updated Readme file(s)"
            git push $(Build.Repository.Uri) HEAD:$(Build.SourceBranch)
